### ISSUE TITLE
Wave propagation in particle assemblies and dynamic boundary conditions

### ISSUE THREAD

**Issue by crest2014** [woodem/woo#13]
According to the manual of PLAXIS, a FEM package, most widely used boundary conditions(BC) are visous boundary and free field boundary.
(a)Viscous boundaries(quiet boundaries, or absorbing boundaries)
A viscous boundary consists of viscous dampers applied in x and y direction along the boundary. Viscous boundaries absorb the incoming wave energy. The viscous boundary conditions are in general used for problems where the dynamic source is inside the mesh.
(b)Free field
The free field boundary conditions are only available for the lateral boundaries. The free field boundaries are made up of a combination of a load history and a viscous boundary. The load history is the load coming from the free field motion at this level. The combination of a load history and a viscous boundary allows for an input of an earthquake motion while still absorbing incoming waves. This option is in general preferred for earthquake analysis.
![free field](https://cloud.githubusercontent.com/assets/9580677/9426551/11353812-4908-11e5-8103-31cafef3da5f.png)
                                                                   ( by FLAC3D manual)

As for DEM simulation, viscous boundaries(quiet boundaries,or absorbing boundaries) are always set for dynamic simulation. The setting of viscous boundary is typically based on the research result of Lysmer and Kuhlemeyer(1969). 
1D absorbing boundaries setting is the simplest situation, which can be deduced analytically by dynamic function and it has been implemented by PFC(also see FLAC manual). In its example of wave propagating in a bar made up of a row of 50 bonded particles, the ball at left-hand end is applied by the dynamic force as well as absorbing boundary:
![qq 20150822204326](https://cloud.githubusercontent.com/assets/9580677/9426681/7c802450-490e-11e5-8a75-cd422c64c9fe.jpg)
C is the P wave speed, ρ is the particle's density, U is the wave displacement function, u is particle's displacement.

2D and 3D absorbing boundaries setting will be much more complicated. FLAC(a finite difference element package) has some attempt, which can be seen from its manual, but it seems that nothing has been clearly described. 

Refferences:
Lysmer, J., and Kuhlemeyer, R. L. (1969). “Finite-dynamic model for infinite media.” J. Eng. Mech. Div., 95(4), 859-877.
Absorbing Boundary Conditions for Seismic Analysis in ABAQUS_2006_babtie
An Energy Absorbing Far-Field Boundary Condition for the ElasticWave Equation
Finite-Dynamic Model for Infinite Media:Corrected Solution of Viscous Boundary Efficiency_2011

**Comment by eudoxos** [comment]
This seems to be more a research topic than just a thing to implement. The codes you reference are based on continuum dynamics (FLAC is finite element code, not finite differences; the same for Plaxis) and their numerical things are not directly transferrable.

**Comment by crest2014** [comment]
At present, only 1D absorbing boundaries has been implemented by PFC, i.e. the second term of the above function F. The minus viscous force can cancel the energy of the reflecting wave out basically.
All of PFC, FLAC(the official website declares that it is an explicit finite difference program),and ABAQUS use the same method as well as the same fomula for viscous force application at the absorbing boundaries. I think, the main difference of boundary forces loading between FEM and DEM is that,the force bearing objects for FEM are Guass points, while  they are particle centers for DEM. Anyway, we can try to reproduce the 1D obsorbing boundaries for Woo.

**Comment by eudoxos** [comment]
You're right with FLAC, I confused it with 3dec for some reason.

I'd propose to close this as issue of Woo, it is a research topic which you have to do by yourself.

That said, if you go that way, feel free to discuss how to best implement such a thing inside Woo (by re-opening the issue or asking on the forum); the framework should be pretty flexible to absorb that as an additional component, once you have it ready in terms of math.

(footnote: The problem seems to be that one is trying to simulate something non-physical (there is no such boundary in reality), but using physical framework and assumptions, so you see that there is a problem from the very start. Even if you managed to have a formulation for 3d dynamics, it wouldn't translate directly to DEM (that is more a mass-spring system than continuum). People tried different things (look at Daudeville & Rousseau who were interfacing DEM with elastic FEM boundary and had the problem of reflection; it is more a numerical hack than something else). I wouldn't take PFC as authoritative for physical correctness, but they are good at twisted but practical solutions ;) )
