### ISSUE TITLE
CMAKE_INSTALL_PREFIX not honored

### ISSUE THREAD

**Issue by mboisson** [woodem/woo#37]
I am trying to install Woo for a user (one of your customers). I use: 

```
cmake -Dpybind11_DIR=$PWD/../build_venv/lib/python3.8/site-packages/pybind11/share/cmake/pybind11 -DWOO_QT5=OFF -DCMAKE_INSTALL_PREFIX=$HOME/woo ..
``` 
but `CMAKE_INSTALL_PREFIX` is not honored: 
```
-- Python modules to be installed in /usr/lib64/python3.6/site-packages/woo (scheme: posix_prefix)
-- Executables to be installed in /usr/bin (scheme: posix_prefix)
``` 

How do I specify where to install it ?

**Comment by eudoxos** [comment]
`WOO_INSTALL_SCEHEME` is used to set [installation sceheme](https://docs.python.org/3/library/sysconfig.html#installation-paths): 

https://github.com/woodem/woo/blob/2fc1c90b0bd544039c6a40ab7edff56b4bfe0da3/CMakeLists.txt#L13

Since you have `posix_prefix` without specifying `WOO_INSTALL_SCEHEME`, you are probably running in python virtual environments where different rules apply:

https://github.com/woodem/woo/blob/2fc1c90b0bd544039c6a40ab7edff56b4bfe0da3/CMakeLists.txt#L19-L24

In that case you *have* to set `PYTHON_EXECUTABLE` to the venv's interpreter (as mentioned in [Installation instructions](https://woodem.org/user/installation.html#compilation-from-source)), likely something like `-DPYTHON_EXECUTABLE=$PWD/../build_venv/bin/python`. This is to make the build predictable so that venv to use is not deduced from the current venv.

The installation directories themselves are queried from Python interpreter here, as Woo is really a (compiled) python module (plus a few executable scripts around that):

https://github.com/woodem/woo/blob/2fc1c90b0bd544039c6a40ab7edff56b4bfe0da3/CMakeLists.txt#L193-L204

**Comment by eudoxos** [comment]
> I am not sure why the `PYTHON_EXECUTABLE` is not found automatically (a simple `which python` will do that), but that allowed me to work around the issue.

`which python` happened to work in your case, but would fail in others — as for instance in stock Ubuntu installation, where the system-wide interpreter is called `python3`.

What is the `CPATH=...` with numpy, its headers were not found automatically?

**Comment by mboisson** [comment]
> > I am not sure why the `PYTHON_EXECUTABLE` is not found automatically (a simple `which python` will do that), but that allowed me to work around the issue.
> 
> `which python` happened to work in your case, but would fail in others — as for instance in stock Ubuntu installation, where the system-wide interpreter is called `python3`.

I see. I guess one could figure out something like detecting `python` and if not `python3` (or the other way around). 

> What is the `CPATH=...` with numpy, its headers were not found automatically?

No, the headers are installed inside of some deep folders in a `site-packages`, and those are not in the `CPATH`, so compilers can't find them automagically.

**Comment by eudoxos** [comment]
>  guess one could figure out something like detecting `python` and if not `python3` (or the other way around).

That would be perhaps "too smart", and would depend on which virtual environment happens to be activate. While it is normal for setup.py-based project, it would be highly unusual and unexpected for CMake, I think.

> the headers are installed inside of some deep folders in a site-packages, and those are not in the CPATH, so compilers can't find them automagically.

Good point. I tried [to integrate this into `CMakeLists.txt`](https://github.com/woodem/woo/commit/d57ce8d073cf9c1b5c4d5277051d3a52333c1275#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) for both numpy (where I always used system version, and since its ABI is very stable, it never crashed even if different library was used) and for pybind11 (which I never used as installed via python package, since it is really just c++ headers). So next time the `CPATH` and `pybind11_DIR` should not be necessary at all, just `PYTHON_EXECUTABLE`.

Thanks for valuable input, I will close this issue now. Feel free to re-open or submit a new issue as needed.
